/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryResourceAttributes {
    /// The name of this category as seen in the Up application. 
    #[serde(rename = "name")]
    pub name: String,
}

impl CategoryResourceAttributes {
    pub fn new(name: String) -> CategoryResourceAttributes {
        CategoryResourceAttributes {
            name,
        }
    }
}


