/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateWebhookRequest : Request to create a new webhook. This currently only requires a `url` attribute. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequest {
    #[serde(rename = "data")]
    pub data: Box<crate::models::WebhookInputResource>,
}

impl CreateWebhookRequest {
    /// Request to create a new webhook. This currently only requires a `url` attribute. 
    pub fn new(data: crate::models::WebhookInputResource) -> CreateWebhookRequest {
        CreateWebhookRequest {
            data: Box::new(data),
        }
    }
}


