/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateWebhookResponse : Successful response after creating a webhook. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::WebhookResource>,
}

impl CreateWebhookResponse {
    /// Successful response after creating a webhook. 
    pub fn new(data: crate::models::WebhookResource) -> CreateWebhookResponse {
        CreateWebhookResponse {
            data: Box::new(data),
        }
    }
}


