/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetAccountResponse : Successful response to get a single account. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::AccountResource>,
}

impl GetAccountResponse {
    /// Successful response to get a single account. 
    pub fn new(data: crate::models::AccountResource) -> GetAccountResponse {
        GetAccountResponse {
            data: Box::new(data),
        }
    }
}


