/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TagResource : Provides information about a tag. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagResource {
    /// The type of this resource: `tags`
    #[serde(rename = "type")]
    pub r#type: String,
    /// The label of the tag, which also acts as the tag’s unique identifier. 
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::AccountResourceRelationships>,
}

impl TagResource {
    /// Provides information about a tag. 
    pub fn new(r#type: String, id: String, relationships: crate::models::AccountResourceRelationships) -> TagResource {
        TagResource {
            r#type,
            id,
            relationships: Box::new(relationships),
        }
    }
}


