/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionResourceRelationships {
    #[serde(rename = "account")]
    pub account: Box<crate::models::TransactionResourceRelationshipsAccount>,
    #[serde(rename = "transferAccount")]
    pub transfer_account: Box<crate::models::TransactionResourceRelationshipsTransferAccount>,
    #[serde(rename = "category")]
    pub category: Box<crate::models::TransactionResourceRelationshipsCategory>,
    #[serde(rename = "parentCategory")]
    pub parent_category: Box<crate::models::CategoryResourceRelationshipsParent>,
    #[serde(rename = "tags")]
    pub tags: Box<crate::models::TransactionResourceRelationshipsTags>,
}

impl TransactionResourceRelationships {
    pub fn new(account: crate::models::TransactionResourceRelationshipsAccount, transfer_account: crate::models::TransactionResourceRelationshipsTransferAccount, category: crate::models::TransactionResourceRelationshipsCategory, parent_category: crate::models::CategoryResourceRelationshipsParent, tags: crate::models::TransactionResourceRelationshipsTags) -> TransactionResourceRelationships {
        TransactionResourceRelationships {
            account: Box::new(account),
            transfer_account: Box::new(transfer_account),
            category: Box::new(category),
            parent_category: Box::new(parent_category),
            tags: Box::new(tags),
        }
    }
}


