/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransactionResourceAttributesHoldInfo : If this transaction is currently in the `HELD` status, or was ever in the `HELD` status, the `amount` and `foreignAmount` of the transaction while `HELD`. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionResourceAttributesHoldInfo {
    #[serde(rename = "amount")]
    pub amount: Box<crate::models::MoneyObject>,
    #[serde(rename = "foreignAmount", deserialize_with = "Option::deserialize")]
    pub foreign_amount: Option<Box<crate::models::HoldInfoObjectForeignAmount>>,
}

impl TransactionResourceAttributesHoldInfo {
    /// If this transaction is currently in the `HELD` status, or was ever in the `HELD` status, the `amount` and `foreignAmount` of the transaction while `HELD`. 
    pub fn new(amount: crate::models::MoneyObject, foreign_amount: Option<crate::models::HoldInfoObjectForeignAmount>) -> TransactionResourceAttributesHoldInfo {
        TransactionResourceAttributesHoldInfo {
            amount: Box::new(amount),
            foreign_amount: if let Some(x) = foreign_amount {Some(Box::new(x))} else {None},
        }
    }
}


