/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionResourceRelationshipsCategoryLinks {
    /// The link to retrieve or modify linkage between this resources and the related resource(s) in this relationship. 
    #[serde(rename = "self")]
    pub param_self: String,
    /// The link to retrieve the related resource(s) in this relationship. 
    #[serde(rename = "related", skip_serializing_if = "Option::is_none")]
    pub related: Option<String>,
}

impl TransactionResourceRelationshipsCategoryLinks {
    pub fn new(param_self: String) -> TransactionResourceRelationshipsCategoryLinks {
        TransactionResourceRelationshipsCategoryLinks {
            param_self,
            related: None,
        }
    }
}


