/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpdateTransactionCategoryRequestData : The category to set on the transaction. Set this entire key to `null` de-categorize a transaction. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTransactionCategoryRequestData {
    /// The type of this resource: `categories`
    #[serde(rename = "type")]
    pub r#type: String,
    /// The unique identifier of the category, as returned by the `/categories` endpoint. 
    #[serde(rename = "id")]
    pub id: String,
}

impl UpdateTransactionCategoryRequestData {
    /// The category to set on the transaction. Set this entire key to `null` de-categorize a transaction. 
    pub fn new(r#type: String, id: String) -> UpdateTransactionCategoryRequestData {
        UpdateTransactionCategoryRequestData {
            r#type,
            id,
        }
    }
}


