/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookEventTypeEnum : Specifies the type of a webhook event. This can be used to determine what action to take in response to the event, such as which relationships to expect. 

/// Specifies the type of a webhook event. This can be used to determine what action to take in response to the event, such as which relationships to expect. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookEventTypeEnum {
    #[serde(rename = "TRANSACTION_CREATED")]
    TransactionCreated,
    #[serde(rename = "TRANSACTION_SETTLED")]
    TransactionSettled,
    #[serde(rename = "TRANSACTION_DELETED")]
    TransactionDeleted,
    #[serde(rename = "PING")]
    Ping,

}

impl ToString for WebhookEventTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::TransactionCreated => String::from("TRANSACTION_CREATED"),
            Self::TransactionSettled => String::from("TRANSACTION_SETTLED"),
            Self::TransactionDeleted => String::from("TRANSACTION_DELETED"),
            Self::Ping => String::from("PING"),
        }
    }
}

impl Default for WebhookEventTypeEnum {
    fn default() -> WebhookEventTypeEnum {
        Self::TransactionCreated
    }
}




