/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookEventResource : Provides the event data used in asynchronous webhook event callbacks to subscribed endpoints. Webhooks events have defined `eventType`s and may optionally relate to other resources within the Up API. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookEventResource {
    /// The type of this resource: `webhook-events`
    #[serde(rename = "type")]
    pub r#type: String,
    /// The unique identifier for this event. This will remain constant across delivery retries. 
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::WebhookEventResourceAttributes>,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::WebhookEventResourceRelationships>,
}

impl WebhookEventResource {
    /// Provides the event data used in asynchronous webhook event callbacks to subscribed endpoints. Webhooks events have defined `eventType`s and may optionally relate to other resources within the Up API. 
    pub fn new(r#type: String, id: String, attributes: crate::models::WebhookEventResourceAttributes, relationships: crate::models::WebhookEventResourceRelationships) -> WebhookEventResource {
        WebhookEventResource {
            r#type,
            id,
            attributes: Box::new(attributes),
            relationships: Box::new(relationships),
        }
    }
}


