/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookDeliveryStatusEnum : Specifies the nature of the success or failure of a webhook delivery attempt to the subscribed webhook URL. The currently returned values are described below:  - **`DELIVERED`**: The event was delivered to the webhook URL   successfully and a `200` response was received. - **`UNDELIVERABLE`**: The webhook URL was not reachable, or timed out. - **`BAD_RESPONSE_CODE`**: The event was delivered to the webhook URL   but a non-`200` response was received. 

/// Specifies the nature of the success or failure of a webhook delivery attempt to the subscribed webhook URL. The currently returned values are described below:  - **`DELIVERED`**: The event was delivered to the webhook URL   successfully and a `200` response was received. - **`UNDELIVERABLE`**: The webhook URL was not reachable, or timed out. - **`BAD_RESPONSE_CODE`**: The event was delivered to the webhook URL   but a non-`200` response was received. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookDeliveryStatusEnum {
    #[serde(rename = "DELIVERED")]
    Delivered,
    #[serde(rename = "UNDELIVERABLE")]
    Undeliverable,
    #[serde(rename = "BAD_RESPONSE_CODE")]
    BadResponseCode,

}

impl ToString for WebhookDeliveryStatusEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Delivered => String::from("DELIVERED"),
            Self::Undeliverable => String::from("UNDELIVERABLE"),
            Self::BadResponseCode => String::from("BAD_RESPONSE_CODE"),
        }
    }
}

impl Default for WebhookDeliveryStatusEnum {
    fn default() -> WebhookDeliveryStatusEnum {
        Self::Delivered
    }
}




