/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AccountResource : Provides information about an Up bank account. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountResource {
    /// The type of this resource: `accounts`
    #[serde(rename = "type")]
    pub r#type: String,
    /// The unique identifier for this account. 
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::AccountResourceAttributes>,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::AccountResourceRelationships>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::AccountResourceLinks>>,
}

impl AccountResource {
    /// Provides information about an Up bank account. 
    pub fn new(r#type: String, id: String, attributes: crate::models::AccountResourceAttributes, relationships: crate::models::AccountResourceRelationships) -> AccountResource {
        AccountResource {
            r#type,
            id,
            attributes: Box::new(attributes),
            relationships: Box::new(relationships),
            links: None,
        }
    }
}


