/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AccountTypeEnum : Specifies the type of bank account. Currently returned values are `SAVER` and `TRANSACTIONAL`. 

/// Specifies the type of bank account. Currently returned values are `SAVER` and `TRANSACTIONAL`. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountTypeEnum {
    #[serde(rename = "SAVER")]
    Saver,
    #[serde(rename = "TRANSACTIONAL")]
    Transactional,

}

impl ToString for AccountTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Saver => String::from("SAVER"),
            Self::Transactional => String::from("TRANSACTIONAL"),
        }
    }
}

impl Default for AccountTypeEnum {
    fn default() -> AccountTypeEnum {
        Self::Saver
    }
}




