/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountResourceAttributes {
    /// The name associated with the account in the Up application. 
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "accountType")]
    pub account_type: crate::models::AccountTypeEnum,
    #[serde(rename = "ownershipType")]
    pub ownership_type: crate::models::OwnershipTypeEnum,
    #[serde(rename = "balance")]
    pub balance: Box<crate::models::MoneyObject>,
    /// The date-time at which this account was first opened. 
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl AccountResourceAttributes {
    pub fn new(display_name: String, account_type: crate::models::AccountTypeEnum, ownership_type: crate::models::OwnershipTypeEnum, balance: crate::models::MoneyObject, created_at: String) -> AccountResourceAttributes {
        AccountResourceAttributes {
            display_name,
            account_type,
            ownership_type,
            balance: Box::new(balance),
            created_at,
        }
    }
}


