/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CategoryResource : Provides information about a category and its ancestry. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryResource {
    /// The type of this resource: `categories`
    #[serde(rename = "type")]
    pub r#type: String,
    /// The unique identifier for this category. This is a human-readable but URL-safe value. 
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::CategoryResourceAttributes>,
    #[serde(rename = "relationships")]
    pub relationships: Box<crate::models::CategoryResourceRelationships>,
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Box<crate::models::AccountResourceLinks>>,
}

impl CategoryResource {
    /// Provides information about a category and its ancestry. 
    pub fn new(r#type: String, id: String, attributes: crate::models::CategoryResourceAttributes, relationships: crate::models::CategoryResourceRelationships) -> CategoryResource {
        CategoryResource {
            r#type,
            id,
            attributes: Box::new(attributes),
            relationships: Box::new(relationships),
            links: None,
        }
    }
}


