/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryResourceRelationshipsChildrenDataInner {
    /// The type of this resource: `categories`
    #[serde(rename = "type")]
    pub r#type: String,
    /// The unique identifier of the resource within its type. 
    #[serde(rename = "id")]
    pub id: String,
}

impl CategoryResourceRelationshipsChildrenDataInner {
    pub fn new(r#type: String, id: String) -> CategoryResourceRelationshipsChildrenDataInner {
        CategoryResourceRelationshipsChildrenDataInner {
            r#type,
            id,
        }
    }
}


