/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoryResourceRelationships {
    #[serde(rename = "parent")]
    pub parent: Box<crate::models::CategoryResourceRelationshipsParent>,
    #[serde(rename = "children")]
    pub children: Box<crate::models::CategoryResourceRelationshipsChildren>,
}

impl CategoryResourceRelationships {
    pub fn new(parent: crate::models::CategoryResourceRelationshipsParent, children: crate::models::CategoryResourceRelationshipsChildren) -> CategoryResourceRelationships {
        CategoryResourceRelationships {
            parent: Box::new(parent),
            children: Box::new(children),
        }
    }
}


