/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ErrorResponse : Generic error response that returns one or more errors. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// The list of errors returned in this response. 
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::ErrorObject>,
}

impl ErrorResponse {
    /// Generic error response that returns one or more errors. 
    pub fn new(errors: Vec<crate::models::ErrorObject>) -> ErrorResponse {
        ErrorResponse {
            errors,
        }
    }
}


