/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetTransactionResponse : Successful response to get a single transaction. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTransactionResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::TransactionResource>,
}

impl GetTransactionResponse {
    /// Successful response to get a single transaction. 
    pub fn new(data: crate::models::TransactionResource) -> GetTransactionResponse {
        GetTransactionResponse {
            data: Box::new(data),
        }
    }
}


