/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetCategoryResponse : Successful response to get a single category and its ancestry. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCategoryResponse {
    #[serde(rename = "data")]
    pub data: Box<crate::models::CategoryResource>,
}

impl GetCategoryResponse {
    /// Successful response to get a single category and its ancestry. 
    pub fn new(data: crate::models::CategoryResource) -> GetCategoryResponse {
        GetCategoryResponse {
            data: Box::new(data),
        }
    }
}


