/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HoldInfoObject : Provides information about the amount at which a transaction was in the `HELD` status. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct HoldInfoObject {
    #[serde(rename = "amount")]
    pub amount: Box<crate::models::MoneyObject>,
    #[serde(rename = "foreignAmount", deserialize_with = "Option::deserialize")]
    pub foreign_amount: Option<Box<crate::models::HoldInfoObjectForeignAmount>>,
}

impl HoldInfoObject {
    /// Provides information about the amount at which a transaction was in the `HELD` status. 
    pub fn new(amount: crate::models::MoneyObject, foreign_amount: Option<crate::models::HoldInfoObjectForeignAmount>) -> HoldInfoObject {
        HoldInfoObject {
            amount: Box::new(amount),
            foreign_amount: if let Some(x) = foreign_amount {Some(Box::new(x))} else {None},
        }
    }
}


