/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListWebhookDeliveryLogsResponse : Successful response to get all delivery logs for a webhook. This returns a paginated list of delivery logs, which can be scrolled by following the `next` and `prev` links if present. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWebhookDeliveryLogsResponse {
    /// The list of delivery logs returned in this response. 
    #[serde(rename = "data")]
    pub data: Vec<crate::models::WebhookDeliveryLogResource>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::ListAccountsResponseLinks>,
}

impl ListWebhookDeliveryLogsResponse {
    /// Successful response to get all delivery logs for a webhook. This returns a paginated list of delivery logs, which can be scrolled by following the `next` and `prev` links if present. 
    pub fn new(data: Vec<crate::models::WebhookDeliveryLogResource>, links: crate::models::ListAccountsResponseLinks) -> ListWebhookDeliveryLogsResponse {
        ListWebhookDeliveryLogsResponse {
            data,
            links: Box::new(links),
        }
    }
}


