/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning.
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// ListTransactionsResponse : Successful response to get all transactions. This returns a paginated list of transactions, which can be scrolled by following the `prev` and `next` links if present.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTransactionsResponse {
    /// The list of transactions returned in this response.
    #[serde(rename = "data")]
    pub data: Vec<crate::models::TransactionResource>,
    #[serde(rename = "links")]
    pub links: Box<crate::models::ListAccountsResponseLinks>,
}

impl ListTransactionsResponse {
    /// Successful response to get all transactions. This returns a paginated list of transactions, which can be scrolled by following the `prev` and `next` links if present.
    pub fn new(data: Vec<crate::models::TransactionResource>, links: crate::models::ListAccountsResponseLinks) -> ListTransactionsResponse {
        ListTransactionsResponse {
            data,
            links: Box::new(links),
        }
    }
}

