/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListCategoriesResponse : Successful response to get all categories and their ancestry. The returned list is not paginated. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListCategoriesResponse {
    /// The list of categories returned in this response. 
    #[serde(rename = "data")]
    pub data: Vec<crate::models::CategoryResource>,
}

impl ListCategoriesResponse {
    /// Successful response to get all categories and their ancestry. The returned list is not paginated. 
    pub fn new(data: Vec<crate::models::CategoryResource>) -> ListCategoriesResponse {
        ListCategoriesResponse {
            data,
        }
    }
}


