/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PingResponseMeta {
    /// The unique identifier of the authenticated customer. 
    #[serde(rename = "id")]
    pub id: String,
    /// A cute emoji that represents the response status. 
    #[serde(rename = "statusEmoji")]
    pub status_emoji: String,
}

impl PingResponseMeta {
    pub fn new(id: String, status_emoji: String) -> PingResponseMeta {
        PingResponseMeta {
            id,
            status_emoji,
        }
    }
}


