/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PingResponse : Basic ping response to verify authentication. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PingResponse {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::PingResponseMeta>,
}

impl PingResponse {
    /// Basic ping response to verify authentication. 
    pub fn new(meta: crate::models::PingResponseMeta) -> PingResponse {
        PingResponse {
            meta: Box::new(meta),
        }
    }
}


