/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RoundUpObject : Provides information about how a Round Up was applied, such as whether or not a boost was included in the Round Up. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoundUpObject {
    #[serde(rename = "amount")]
    pub amount: Box<crate::models::MoneyObject>,
    #[serde(rename = "boostPortion", deserialize_with = "Option::deserialize")]
    pub boost_portion: Option<Box<crate::models::RoundUpObjectBoostPortion>>,
}

impl RoundUpObject {
    /// Provides information about how a Round Up was applied, such as whether or not a boost was included in the Round Up. 
    pub fn new(amount: crate::models::MoneyObject, boost_portion: Option<crate::models::RoundUpObjectBoostPortion>) -> RoundUpObject {
        RoundUpObject {
            amount: Box::new(amount),
            boost_portion: if let Some(x) = boost_portion {Some(Box::new(x))} else {None},
        }
    }
}


