/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionResourceRelationshipsTagsLinks {
    /// The link to retrieve or modify linkage between this resources and the related resource(s) in this relationship. 
    #[serde(rename = "self")]
    pub param_self: String,
}

impl TransactionResourceRelationshipsTagsLinks {
    pub fn new(param_self: String) -> TransactionResourceRelationshipsTagsLinks {
        TransactionResourceRelationshipsTagsLinks {
            param_self,
        }
    }
}


