/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookInputResource : Represents a webhook specified as request input. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookInputResource {
    #[serde(rename = "attributes")]
    pub attributes: Box<crate::models::WebhookInputResourceAttributes>,
}

impl WebhookInputResource {
    /// Represents a webhook specified as request input. 
    pub fn new(attributes: crate::models::WebhookInputResourceAttributes) -> WebhookInputResource {
        WebhookInputResource {
            attributes: Box::new(attributes),
        }
    }
}


