/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookEventResourceAttributes {
    #[serde(rename = "eventType")]
    pub event_type: crate::models::WebhookEventTypeEnum,
    /// The date-time at which this event was generated. 
    #[serde(rename = "createdAt")]
    pub created_at: String,
}

impl WebhookEventResourceAttributes {
    pub fn new(event_type: crate::models::WebhookEventTypeEnum, created_at: String) -> WebhookEventResourceAttributes {
        WebhookEventResourceAttributes {
            event_type,
            created_at,
        }
    }
}


