/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookEventCallback : Asynchronous callback request used for webhook event delivery. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookEventCallback {
    #[serde(rename = "data")]
    pub data: Box<crate::models::WebhookEventResource>,
}

impl WebhookEventCallback {
    /// Asynchronous callback request used for webhook event delivery. 
    pub fn new(data: crate::models::WebhookEventResource) -> WebhookEventCallback {
        WebhookEventCallback {
            data: Box::new(data),
        }
    }
}


