/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WebhookDeliveryLogResourceAttributesRequest : Information about the request that was sent to the webhook URL. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookDeliveryLogResourceAttributesRequest {
    /// The payload that was sent in the request body. 
    #[serde(rename = "body")]
    pub body: String,
}

impl WebhookDeliveryLogResourceAttributesRequest {
    /// Information about the request that was sent to the webhook URL. 
    pub fn new(body: String) -> WebhookDeliveryLogResourceAttributesRequest {
        WebhookDeliveryLogResourceAttributesRequest {
            body,
        }
    }
}


