/*
 * Up API
 *
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookInputResourceAttributes {
    /// The URL that this webhook should post events to. This must be a valid HTTP or HTTPS URL that does not exceed 300 characters in length. 
    #[serde(rename = "url")]
    pub url: String,
    /// An optional description for this webhook, up to 64 characters in length. 
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl WebhookInputResourceAttributes {
    pub fn new(url: String) -> WebhookInputResourceAttributes {
        WebhookInputResourceAttributes {
            url,
            description: None,
        }
    }
}


